name: My First CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Verify AWS Authentication
      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      # Copy index.html to EC2
      - name: Copy Website to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "index.html"
          target: "/home/ubuntu/"

      # Deploy website
      - name: Deploy Website
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo cp /home/ubuntu/index.html /var/www/html/index.html
            sudo systemctl reload nginx

      # Display Message
      - name: Display Message
        run: echo "Hello DevOps! My first GitHub Actions workflow is running."

      # Show Current Directory
      - name: Show Current Directory
        run: pwd

      # List Repository Files
      - name: List Repository Files
        run: ls -la

      # Show Date
      - name: Show Date
        run: date
